#!/bin/bash

set -eEuo pipefail

readonly reporoot=$(readlink -f $(dirname $0))

create_symlink () {
    local -r src_file="$1"
    local -r dst_file="${HOME}/${1#${reporoot}/files/}"
    local -r dst_dir="$(dirname "$dst_file")"
    [[ -d $dst_dir ]] || mkdir -p "$dst_dir"
    ln -s "$src_file" "dst_file"
}

check_file() {
    local -r src_file="$1"
    local -r dst_file="${HOME}/${1#${reporoot}/files/}"

    if [[ -e "$dst_file" ]]; then
        printf '%s: File already exists\n' "$dst_file"
	return 1
    fi
}

check_failed=0

while IFS= read -r -d '' file; do
    if ! check_file "$file"; then
        check_failed=1
    fi
done < <(find "${reporoot}/files" -print0)

if (( check_failed )); then
    printf 'Could not link all files, so nothing done\n'
    exit 1
fi

for IFS= read -r -d '' file; do
    create_symlink "$file"
done < <(find "${reporoot}/files" -print0)

printf 'All files linked\n'

######################################################################
# vim: set tabstop=4 expandtab shiftwidth=4
